version: "3"
services:
  # 服务名称
  nexus3:
    # 镜像
    image: sonatype/nexus3:3.58.1
    # 容器名称
    container_name: nexus3
    # 设置容器的权限为root
    privileged: true
    # 重启策略
    restart: on-failure
    # 端口映射
    ports:
      # web服务使用
      - "8081:8081"
      # http仓库使用
      - "8082:8082"
      # https仓库使用
      - "200:200"
    # 挂载数据卷
    volumes:
      # 将主机的/opt/neuxus3/data目录挂载映射到容器的/nexus-data目录
      - /opt/nexus3/nexus-data:/nexus-data
    # 设置环境变量
    environment:
      # 配置nexus3服务的内存，避免小规格机器崩掉
      INSTALL4J_ADD_VM_PARAMS: "-Xms512m -Xmx512m -XX:MaxDirectMemorySize=512m -Djava.util.prefs.userRoot=/nexus-data/javaprefs"
