version: '3'
services:
  nginx_web:
    image: nginx:latest
    container_name: nginx
    privileged: true
    restart: on-failure
    volumes:
      - "./conf/nginx.conf:/etc/nginx/nginx.conf"
      - "./conf/conf.d:/etc/nginx/conf.d"
      - "./cert:/etc/nginx/cert"
      - "./log:/var/log/nginx"
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
    hostname: nginx
    networks:
      - nginx_net
    ports:
      - 80:80
      - 443:443
    logging:
      driver: "json-file"
      options:
        max-size: "512m"

networks:
  nginx_net:
